version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./theeye:/theeye
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - theeye

  redis:
    image: redis:alpine
    networks:
      - theeye

  rabbitmq:
    image: rabbitmq:alpine
    restart: always
    ports:
      - "5672:5672"
    networks:
      - theeye

  celery:
    restart: always
    build:
      context: .
    command: celery -A theeye worker -l INFO
    volumes:
      - ./theeye:/theeye
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
      - web
    networks:
      - theeye

  db:
    hostname: theeye_db_1
    image: postgres:14.0-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
    networks:
      - theeye


networks:
  theeye:
    driver: bridge

volumes:
  db: