version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./theeye:/theeye
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - theeye

  redis:
    image: redis:alpine
    networks:
      - theeye


networks:
  theeye:
    driver: bridge