# Generated by Django 3.2.8 on 2021-10-26 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='eventerror',
            options={'ordering': ['-created_at']},
        ),
    ]
